[project]
name = "project-s"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.8.4",
    "langchain-ollama>=1.0.0",
]
